repository:
  auto_init: true
  description: "Default description"
  homepage: "https://example.github.io/"
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  default_branch: main
  gitignore_template: node
  license_template: mit
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true

labels:
  - name: bug
    color: CC0000
    description: An issue with the system
  - name: feature
    color: 336699
    description: New functionality
  - name: first-timers-only
    oldname: Help Wanted
    color: 326699
